### ISSUE TITLE
All zero values too need to be poll and written together with date in a DB.

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#15]
For some reason in any way it is impossible to create poolrequest therefore I write here...

Bug...
...It is necessary to do check on NULL, but not on zero (0) values when polling. Otherwise, if all values zero (0), in a DB it isn't write information on the current polling. There can be a situation when in cabnavigator or when viewing CDU tooltip the last **nonzero** value for **some** **long** **ago** passed date is displayed :-/. I.e., for example, the current consumption of CDU is zero, and is displayed wrong nonzero value for some long ago passed date.

Result: in all type MeasurePoint have to be poll and write to the DB with the current date and time, isn't dependent on that zero values or not.

The diff-file with changes:
$diff measure.inc.php measure.inc.php.new > measure.inc.php.diff

641,642c641,642
<               if($values[0]!=false || $values[1]!=false || $values[2]!=false){
## <                       $m->Wattage1=intval($values[0] \* $this->PowerMultiplier);

> ```
>           if(!is_null($values[0]) || !is_null($values[1]) || !is_null($values[2])){
>                   $m->Wattage1=@intval($values[0] * $this->PowerMultiplier);
> ```
> 
> 646c646
> ## <               if($values[3] != false) {
> 
> ```
>           if(!is_null($values[3])) {
> ```
> 
> 648,649c648,650
> <               }
> ## <               else if($values[0]!=false || $values[1]!=false || $values[2]!=false){
> 
> ```
>                   $m->Date=date("Y-m-d H:i:s");
>                   $m->CreateMeasure();
>           }elseif(!is_null($values[0]) || !is_null($values[1]) || !is_null($values[2])){
> ```
> 
> 656,658c657,658
> <               } else {
> <                       //nothing to record
> ## <                       return;
> 
> ```
>                   $m->Date=date("Y-m-d H:i:s");
>                   $m->CreateMeasure();
> ```
> 
> 660,661d659
> <               $m->Date=date("Y-m-d H:i:s");
> <               $m->CreateMeasure();
> 663d660
> <
> 1464c1461
> ## <               if($values[0]!=false || $values[1]!=false) {
> 
> ```
>           if(!is_null($values[0]) || !is_null($values[1])) {
> ```
> 
> 2026c2023
> ## <               if($values[0]!=false || $values[1]!=false) {
> 
> ```
>           if(!is_null($values[0]) || !is_null($values[1])) {
> ```

Very thanks for the support.

**Comment by spezialist1** [comment]
And what reason for reopened?

**Comment by MorinPierre** [comment]
I have some issues with your modifications. I just reopened to remember I have to work on it.
