### ISSUE TITLE
How to correctly polling power and energy for 1ph/3ph CDU aka ElectricalMP?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#16]
Hi Pierre.

I actively test openDCIM with PUE_DCEM and I want to consult to you.

After the last changes, polling for CDU in cabinets it is work through MeasurePoint polling.
For example, at me is in a cabinet 3ph CDU (APC AP8881) which in openDCIM represents as three separate devices (device1 - phase L1 of this 3ph CDU, device2 - phase L2 of this 3ph CDU and device3 - phase L3 of this 3ph CDU). And with device1 power polling on the L1 phase and energy polling in total on this 3ph CDU is working. With device2 and device3 polling only of power on the L2 and on the L3 to phases respectively is working. Such division of one 3ph CDU on three separate devices for me is necessary for the reason that I need to control visually loading on each phase in a cabinet in order that it is correct to power connect the IT equipment.

Now question: as it is correct to me to organize a polling on these three devices if I want to see loading on these three devices with a frequency of updating of five minutes. And besides, I want to see full (totally on all phases) the consumed energy it 3ph CDU, for example, in each hour or per every day or in a month?

Very thanks for the support and you do very useful work :-).

**Comment by MorinPierre** [comment]
hi,

I think this is not possible with the current version of the project. If the only reason you split your CDU in multiple devices is to see the power on each phase in the cabnavigator, then a solution could be to display the power on each phase in the cabnavigator. You will be able to merge your three CDU in one which is better in my opinion.
I'll take care of that before the end of the week.

**Comment by spezialist1** [comment]
I.e., in the future you will make so, if in cabnavigator one 3ph CDU will be as three separate CDU-devices, but they will refer to the same one ElectricalMP (with four OID)?
I correctly understood you?

**Comment by MorinPierre** [comment]
No, you will have one unique CDU with his MeasurePoint with four OID. The cabnavigator will display the three phases and the total.

**Comment by spezialist1** [comment]
Pierre, one bug: when creating new ElectricalMP don't save value of fields SNMP version and SNMP community.

**Comment by spezialist1** [comment]
One more problem...

Pierre, I in openDCIM have cabinets in which conditioners devices are installed. In these cabinets there are 3ph CDU installed on which measurement of power consumption on requirement of cooling of DC is performed. In a cabnavigator visually this information is displayed separately on each of three phases.

If to setup to this 3ph CDU in compliance of ElectricalMP and to specify the category other than 'IT', for example, 'Cooling' (after all energy is consumed for needs of cooling, but not IT equipment), in cabnavigator disappears display of the current power consumption. If in to specify by the specified above ElectricalMP the category 'IT', in cabnavigator there is a display of the current power consumption. But after all the device is the conditioner, and it isn't from the category 'IT'...

Any ideas?
Very thanks for the support.

**Comment by MorinPierre** [comment]
cabnavigator only displays PDU linked to IT ElectricalMeasurePoints. I'll see if I can change that (I don't remember why I did that but there's probably a reason).

**Comment by MorinPierre** [comment]
Please, open a new issue for each problem/suggestion/comment. It's easier to know what I have to fix or add.

**Comment by spezialist1** [comment]
Hi Pierre,

And tell, please, at me value of energy with ElectricalMP are pulling each five minutes. Whether in Graph Generator diagrams of energy in each hour, per every day, etc. will be correctly displayed?

Whether it will also be correct to be executed calculation of energy efficiency?

Very thanks for the support.

**Comment by MorinPierre** [comment]
You can measure energy with the frequency you want. Diagrams and energy efficiency calculation will be correct as long as you measure energy as a counter.
