### ISSUE TITLE
Display power consumption in cabnavigator for not IT equipment?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#17]
Pierre, I will repeat that it was clear further:
# 

Pierre, I in openDCIM have cabinets in which conditioners devices are installed. In these cabinets there are 3ph CDU installed on which measurement of power consumption on requirement of cooling of DC is performed. In a cabnavigator visually this information is displayed separately on each of three phases.
# If to setup to this 3ph CDU in compliance of ElectricalMP and to specify the category other than 'IT', for example, 'Cooling' (after all energy is consumed for needs of cooling, but not IT equipment), in cabnavigator disappears display of the current power consumption. If in to specify by the specified above ElectricalMP the category 'IT', in cabnavigator there is a display of the current power consumption. But after all the device is the conditioner, and it isn't from the category 'IT'...

Pull request #659 doesn't solve this problem, power consumption for air conditioners isn't displayed in cabnavigator. But the problem can be corrected if to make some changes to the GetWattage() function in the power.inc.php file, for example:

instead of

if($mp->Category=="IT") {

this

if($mp->Category=="IT" || $mp->Category=="Cooling") {

I and made and the problem was solved.

Very thanks for the support.

**Comment by MorinPierre** [comment]
You can remove this line. I removed the wrong one in my previous push...

**Comment by spezialist1** [comment]
Ok, thanks.
