### ISSUE TITLE
Power on dial power meter in power panels isn't displayed?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#20]
For ElectricalMP if Equipment Type is Power Panel and Category other than IT or UPS Input, power on dial power meter in power panels isn't displayed. But I have many power panels which are used both for Cooling and for UPS Output and for another.

Very thanks for the support.

**Comment by MorinPierre** [comment]
Are you talking about the gauge in power_panel.php?

**Comment by spezialist1** [comment]
Yes.

14.08.2015 15:12, MorinPierre notifications@github.com

> Are you talking about the gauge in power_panel.php?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/20#issuecomment-131089054

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
FREEhost.UA - быстрый и удобный хостинг доступный каждому.
http://freehost.com.ua/unix/

**Comment by spezialist1** [comment]
Pierre, this gauge also has problems, if language other than en_US :-/. I will send changes which correct this problem later.

Very thanks for the support.

**Comment by MorinPierre** [comment]
Are your Measure points linked to the panel or to devices which are connected to the panel? The gauge uses measures from MP connected to the power panel by default. If there isn't, It will search in the connected devices, mechanical devices and power panels.

**Comment by spezialist1** [comment]
Yes, Measure points linked to the power panel. If in the Measure point settings to specify Category, for example, of 'IT' or 'UPS Input', gauge displays power consumption. If in the Measure point settings to specify Category, for example 'Cooling' or 'UPS Output', gauge shows 0...

**Comment by spezialist1** [comment]
See also #664

**Comment by spezialist1** [comment]
Pierre, actually now all on the contrary, i.e. in power panel is displayed the summ power measured by the connected devices with the MP, but not from MP which is associated with this power panel. And it is incorrect...

Very thanks for the support.

**Comment by MorinPierre** [comment]
See the last commit and tell me what you think about it.

**Comment by spezialist1** [comment]
Ok, now really load in power panels is displayed correctly.

Very thanks for the support.
