### ISSUE TITLE
CDU aka ElectricalMP which have only amperage OID? How?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#21]
Pierre, and how CDU (ElectricalMP) which have only amperage OID are relative? This situation was provided in original openDCIM, and in openDCIM-PUE_DCEM isn't present.
For example, I have many single-phase rPDU APC and a quantity of single-phase APC Smart-UPS which have so-called "power banks" power on which can be calculated only using amperage OID and rated voltage (power OID in this devices simply is absent). These devices at me are CDU and I need to know on them power consumption.

Very thanks for the support.

**Comment by MorinPierre** [comment]
It's not implemented yet. I hope I'll have the time to do it.

**Comment by spezialist1** [comment]
I too very much hope, differently in this case openDCIM-PUE_DCEM will lose to parent openDCIM :-(...

**Comment by spezialist1** [comment]
Since yesterday I implement openDCIM with PUE and DCEM for one DC for bank: unfortunately, there the almost all cabinet rPDUs of APC production of four-five years old, also which have only amperage OID. Hmm...

**Comment by MorinPierre** [comment]
I should be able to add this next week.

**Comment by spezialist1** [comment]
One note: it is necessary to provide not only Amperage OID on each phase, and Voltage OID on each phase.

Very thanks for the support.

**Comment by MorinPierre** [comment]
I think voltage will be a new attribute for ElectricalMP (only displayed when using amperage instead of wattage) as it doesn't change a lot over the time.

**Comment by spezialist1** [comment]
Pierre, I wrote some reasons on the matter here: http://list.opendcim.org/private/discussion/2015-August/002761.html

Very thanks for the support.
