### ISSUE TITLE
Problem with create new Mechanical Device?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#22]
In case of creation of the new mechanical device custom values of the following fields don't save (remain by default):

-- Data Center ID
-- Power Multiplier
-- Energy Multiplier

If to update already created mechanical device, custom values above of the specified fields correctly save.

P.S.: in db-4.1-to-PUE_DCEM.sql need to add folowing:

ALTER TABLE fac_MechanicalDevice ADD PanelID2 int(11) NOT NULL AFTER PanelPole;
ALTER TABLE fac_MechanicalDevice ADD PanelPole2 int(11) NOT NULL AFTER PanelID2;

Very thanks for the support.

**Comment by MorinPierre** [comment]
There's no attribute PowerMultiplier or EnergyMultiplier in MechanicalDevice and DataCenterID saves correctly for me. Are you sure you're talking about the right class?

**Comment by spezialist1** [comment]
Sorry, I wanted to tell to create new ElectricalMP with Equipment Type the Mechanical Device.
