### ISSUE TITLE
To associate one ElectricalMP from several CDU?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#23]
Pierre, I had a situation when there is some CDU in different places of DC, measurements of power and energy on which are actually made by means of one device (for example, CDU in Smart-UPS cabinet which feeds some CDU in Air conditioner cabinet; this two CDU in different cabinets in different rooms is some).
Can make possible to associate the same ElectricalMP from several CDU? Thus it is evident on cabinets their consuming will be visible (by means of the CDU display). And in the ElectricalMP list there will be no duplicating of the same MP. After all a basic purpose of ElectricalMP - computation of PUE and DCEM DC's, after all.

Very thanks for the support.

**Comment by MorinPierre** [comment]
The idea behind measure points is to be able to define a point anywhere in the DC and measure things at this point. As a point can't be at two position at the same time, you can't link a measure point to multiple equipments. You should link your MP to the device which take your measures.

**Comment by spezialist1** [comment]
And how then display of power consumption in cabinets and power panels?
For an example, in a cabinet there is rack PDU which is one ElectricalMP. And at the same time this rack PDU is still Power Panel to which is connected rack ATS. Total, we have one CDU and one Power Panel, but ElectricalMP shall be one. Now it is two different ElectricalMP which are the same device, i.e. rack PDU in a cabinet.

Very thanks for the support.

**Comment by MorinPierre** [comment]
If I understand well, you have a PDU that you consider also as a Power Panel to be able to connect another PDU to it. Am I right?

**Comment by spezialist1** [comment]
Yes, everything is correct: also it is the normal situation provided initially in openDCIM.

17.08.2015 15:47, MorinPierre notifications@github.com

> If I understand well, you have a PDU that you consider also as a Power Panel to be able to connect another PDU to it. Am I right?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/23#issuecomment-131805442

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
Mmmh in my opinion, it is the main branch of openDCIM which has to be changed. With the possibility to connect PDU to each other, you wouldn't have this problem.

**Comment by spezialist1** [comment]
Yes. So far it is a small problem: besides that it is necessary to create some identical ElectricalMP, we have a lot on polling of measuring information from the same devices. Both it isn't good...
