### ISSUE TITLE
Computation of energy for needs of other devices?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#24]
Pierre, and you plan to realize in openDCIM-PUE_DCEM computation of energy for needs of other devices?
For example, I in DC have three ElectricalMP of energy:
1. measurement of energy for DC entirely;
2. measurement of energy for cooling of DC;
3. measurement of energy for IT equipment.

But I have no ElectricalMP of energy which is spent for other needs. But this energy can be expected as a difference between a total energy of DC and energies cooling and IT equipment.
It is possible, of course to create a ElectricalMP of 'Other' and 'Other mechanical' with the fixed power (to enter manually), but it is incorrect: after all consuming within days and during different seasons differs.

**Comment by MorinPierre** [comment]
I won't be able to add this. I'll stop working on this project by the end of the month. 
I suggest that you create a MP and record measures manually (on the bottom of the measure point page) once a month or something like that.

**Comment by spezialist1** [comment]
Pierre, and later you plan to continue again works on this project? After all the project is very good!

**Comment by MorinPierre** [comment]
I won't continue, I hope the community will be able to improve my work. However, I'll keep answering questions.

**Comment by spezialist1** [comment]
I hope that and will be... Anyway thanks for support (in the future :-).
