### ISSUE TITLE
'UPS powered' for air conditioner, powered from the separate UPS?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#25]
Pierre, if the air conditioner is powered from the separate UPS, whether it is necessary to mark in ElectricalMP check box 'UPS powered' for this air conditioner?

Very thanks for the support.

**Comment by MorinPierre** [comment]
You have to check 'UPS powered' when the energy you measure comes from one or more UPS. I'm not sure if it answers your question as I didn't understand it totally (sorry).

**Comment by spezialist1** [comment]
Thanks, you answered my question.

**Comment by spezialist1** [comment]
Pierre, one more question: what category needs to be selected for ElectricalMP which measures the total power/energy consumption of DC?

**Comment by MorinPierre** [comment]
Is it an UPS or a combination of UPS?

**Comment by spezialist1** [comment]
No, it not the UPS. It simply the power/energy measuring instrument (for example Socomec DIRIS multimeter) on an power input of the DC (IT equipment + cooling + other devices...)

**Comment by MorinPierre** [comment]
Yes, but it can be considered as the set of the equipments which doesn't have parent in the energy chain. If all your equipments are powered by UPS (one or more) you can choose UPS Input.

**Comment by spezialist1** [comment]
And if not all equipment are powered by UPS, then that 'none'?

**Comment by MorinPierre** [comment]
If you set the Category to none the MP won't be considered when the PUE or DCEM are calculated. For now, a mixed UPS/nonUPS measure is not precise enough to calculate PUE or DCEM properly. In this case, I suggest setting the category to UPS Input and check UPS powered for each ElectricalMP. Your PUE and DCEM should be correct.

**Comment by spezialist1** [comment]
It is possible to close (see #31).
