### ISSUE TITLE
Graph Generator: the display bug in the browser if is a lot of MP?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#26]
Pierre, if there is a lot of MP, in Graph Generator we have the following bug (I checked in Opera 31 and IE 11):
![graphgenerator1](https://cloud.githubusercontent.com/assets/10425179/9306693/9858c188-4502-11e5-8595-784301df22a6.png)
![graphgenerator2](https://cloud.githubusercontent.com/assets/10425179/9306700/9f45be74-4502-11e5-8eb0-3211588ee406.png)

Very thanks for the support.

**Comment by MorinPierre** [comment]
This problem is not due to the quantity of MP but to the fact that their name is too long. The boxes don't grow when the name needs two lines or more. I hate HTML/CSS... I'll try to find a way to fix this.

**Comment by spezialist1** [comment]
The bug is corrected, thanks.
