### ISSUE TITLE
DataCenterGraph report is not working

### ISSUE THREAD

**Issue by MorinPierre** [MorinPierre/openDCIM#27]
see https://github.com/MorinPierre/openDCIM/commit/251296f51defe4cbf4e659556553f624fde83f69

**Comment by spezialist1** [comment]
Pierre, possibly it is a site specific problem. Here that at me /var/log/messages:

```
Aug 18 16:27:56 opendcim-zt0 kernel: dot[12714]: segfault at 10 ip 00007f136d48b99b sp 00007fff586ff050 error 4 in libgvplugin_dot_layout.so.6.0.0[7f136d47a000+24000]
Aug 18 16:27:57 opendcim-zt0 abrt-hook-ccpp: Saved core dump of pid 12714 (/usr/bin/dot) to /var/tmp/abrt/ccpp-2015-08-18-16:27:56-12714 (15360000 bytes)
Aug 18 16:27:57 opendcim-zt0 dbus-daemon: dbus[784]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Aug 18 16:27:57 opendcim-zt0 dbus[784]: [system] Activating service name='org.fedoraproject.Setroubleshootd' (using servicehelper)
Aug 18 16:27:59 opendcim-zt0 abrt-server: Generating core_backtrace
```

Very thanks for the support.

**Comment by MorinPierre** [comment]
Let's proceed by steps. First we'll test if the dot file is correctly created. Check if line 195 "unlink($dotfile);" is still commented. Execute the script and check /tmp for any dot_\* file. If there is no such file, change line 189 from "$dotfile = tempnam('/tmp/', 'dot_');" to "$dotfile = tempnam('./poll_scripts/', 'dot_');". Run the script again and check poll_scripts folder in your openDCIM folder. Be sure you gave the ownership to apache.

**Comment by spezialist1** [comment]
Pierre, dot_ and graph_ files correctly created in ./poll_scripts folder. But graph_ file with 0 byte.

19.08.2015 10:32, MorinPierre notifications@github.com

> Let's proceed by steps. First we'll test if the dot file is correctly created. Check if line 195 "unlink($dotfile);" is still commented. Execute the script and check /tmp for any dot_\* file. If there is no such file, change line 189 from "$dotfile = tempnam('/tmp/', 'dot_');" to "$dotfile = tempnam('./poll_scripts/', 'dot_');". Run the script again and check poll_scripts folder in your openDCIM folder. Be sure you gave the ownership to apache.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/27#issuecomment-132476545

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
Ok, seems like the script can't create the dot file in /tmp/. It's weird because the network report works and uses the same folder. Maybe your /tmp folder only keeps files during the execution of the script. The dot file would be correctly created but you don't see it because it is removed at the end of the script. Anyway, we're progressing. Can you send me the dot file you got?

**Comment by spezialist1** [comment]
Pierre, ownership apache to the folder /tmp is correctly.
I manually execute this command and segfault:

```
#/usr/bin/dot -Tpng -o graph.fl dot_n9KYSe
...
...
...
Warning: node RPDU2-SH-D4-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D4-(PHASE2), port INOUT unrecognized
Warning: node RPDU2-SH-D5-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-D5-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-D5-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-G1-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-G1-(PHASE1), port INOUT unrecognized
Warning: node RPDU2-SH-G1-(PHASE1), port INOUT unrecognized
Segmentation fault (core dumped)
```

Where RPDU2-SH-D5-(PHASE1) and other is power panels without associated measure point.

Very thanks for the support.

P.S.: I send dot file on your email later.

**Comment by MorinPierre** [comment]
The error probably comes from the dot file creation. With the dot file I should be able to fix it.

**Comment by spezialist1** [comment]
Pierre, how I can send to dot file only you personally?

19.08.2015 12:03, MorinPierre notifications@github.com

> The error probably comes from the dot file creation. With the dot file I should be able to fix it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/27#issuecomment-132501426

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
pmorin@ipsl.jussieu.fr

**Comment by MorinPierre** [comment]
Last commit should fix the problem. Is the graph still readable? I saw you have a lot of equipments.

**Comment by spezialist1** [comment]
Pierre, segfault doesn't appear any more, process 'dot' normally works, but on the DELL R210 server intended only under openDCIM, the report is formed 20 minutes and isn't ready yet. I wait... Probably there is too much equipment... But it is usual average DC and not completely completed :-).

Very thanks for the support.

**Comment by spezialist1** [comment]
After more than 20 minutes of waiting I have this :-)
![strange_report](https://cloud.githubusercontent.com/assets/10425179/9356261/3d38a9da-4688-11e5-8eab-568081d1b310.png)

**Comment by MorinPierre** [comment]
Haha, I think I got a bit too ambitious on this one. I'll remove the devices from the graph. It should be more reasonable.

**Comment by spezialist1** [comment]
I too so think as CDUs and Power Panels so is a lot of, and it is even more much devices :-).

**Comment by spezialist1** [comment]
Unfortunately, the result changed a little: probably there is too much CDUs and Power Panels...

**Comment by MorinPierre** [comment]
The idea was to be able to represent a datacenter by a graph to visualize the energy chain. It could have been usefull for measure points placement.

**Comment by MorinPierre** [comment]
I'll probably remove it...

**Comment by spezialist1** [comment]
Perhaps, it makes sense to do restriction at the level of a zone or the room?
