### ISSUE TITLE
Poll script management: small colored bug?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#28]
Pierre, one more small bug: in poll script management the first existing script always without green mark:
![color_bug](https://cloud.githubusercontent.com/assets/10425179/9354973/69523bd6-467d-11e5-99a3-7867d12f513d.png)

Very thanks for the support.

**Comment by MorinPierre** [comment]
If you look closely the mark is here but for some reason it is crushed. What browser do you use?

**Comment by spezialist1** [comment]
I try in latest Opera 31 and latest IE11 under Windows10: it seems to me that it doesn't depend on the browser...

19.08.2015 15:33, MorinPierre notifications@github.com

> If you look closely the mark is here but for some reason it is crushed. What browser do you use?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/28#issuecomment-132574530

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
Does this bug still appear?

**Comment by spezialist1** [comment]
Yes, this bug still appear...

**Comment by MorinPierre** [comment]
As I can't reproduce this bug here I'll need the source code of the page.
Right click anywhere on the page, choose "inspect element" or something like that. A window containing the source code of the page should open somewhere in your browser. Copy the code in a file and send it to my email address.

**Comment by spezialist1** [comment]
Pierre, the bug reason - length of the name of MP group. If the name too long, colorBox decreases from 6px x 24px to 1px x 24px. Here, look in pictures:

-- normal -->
![colorbox2](https://cloud.githubusercontent.com/assets/10425179/9382055/b7f62f5e-4745-11e5-9a84-be83c5a51837.png)

-- bug -->
![colorbox1](https://cloud.githubusercontent.com/assets/10425179/9382065/ce4f1996-4745-11e5-97f3-91bf4d057ec0.png)

-- after rename MPG -->
![colorbox3](https://cloud.githubusercontent.com/assets/10425179/9382073/e21c9de0-4745-11e5-9959-06c6c55f5c8c.png)

Very thanks for the support.

**Comment by spezialist1** [comment]
Pierre, this fix doesn't delete a bug: I checked twice.

**Comment by MorinPierre** [comment]
I finally found why it was happening. It was due to the size of your window. The way I fixed it is weird and I don't know why it works but it works on both firefox and chromium. Tell it works for you too. Please...

**Comment by spezialist1** [comment]
Pierre, yes, it really helped!

20.08.2015 16:25, MorinPierre notifications@github.com

> Closed #28 via 42fe87c6adefa1792964a261dbcf4b7ade2ad358.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/28#event-387664156

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем
