### ISSUE TITLE
Periodic cleaning tables of measurements?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#29]
Pierre, it would be very good to provide any periodic cleaning of three tables measurements (fac_AirMeasure, fac_CoolingMeasure and fac_ElectricalMeasure) on some condition.
Reason: even if to poll measurement isn't more often than each hour, at a large number of measurement points, three above tables quickly increase, that leads to delay of a response openDCIM server in general.
In openDCIM such problem exists only with the action log table: all other tables have no similar problems with rapid growth of the size.

Very thanks for the support.

**Comment by MorinPierre** [comment]
I'm not sure cleaning the table would be a good solution. Measurements allow to keep a trace of the consumption for calculate DCEM and PUE. Those indicators are more relevant when measures are taken frequently during a year.
Maybe is there a way to keep those data without impacting the performance of the database.

**Comment by spezialist1** [comment]
Yes, the reason in it is. On this matter it is necessary to think still...

P.S.: and for what purposes of ipmitool in configuration page? There is some idea?

**Comment by MorinPierre** [comment]
I'm adding a new connection type for measure points. Still testing it. This file leaked and I was too lazy to remove it...
Consider that as some kind of teasing :)

**Comment by spezialist1** [comment]
Then I still would add type of connection for measure points, for example, "periodic import from the file". I.e., not manual import which already is, and automatic on crond. I already deal with it when I have an equipment which cannot be measured in any way, but I can periodically do some mathematical calculations and then periodically import their result to concrete measure point.

**Comment by spezialist1** [comment]
It is possible to close.
