### ISSUE TITLE
ipmitool: new idea :-).

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#33]
Pierre, concerning implementation of ipmitool. After all, this tool can be used not only for three existing MP types (Electrical, Cooling and Air), and for the new MP type, for example, of 'Number of phisical CPU', 'Phisical CPU load', etc.
I spotted :-) this idea at the APC DC IT Optimize program from the APC DC Operation program complex:
![itoptimize](https://cloud.githubusercontent.com/assets/10425179/9404577/7757859c-47f9-11e5-963a-2634c4ae3e53.jpg)

It is necessary to tell, that actually, the APC DC IT Optimize program it is simple skin for other program Intel DCM: Energy Director:

-- dashboard:
![dcm1](https://cloud.githubusercontent.com/assets/10425179/9404629/d614295a-47f9-11e5-9150-0c3826838cbf.png)
![dcm2](https://cloud.githubusercontent.com/assets/10425179/9404633/dc0eb262-47f9-11e5-9be6-8c773ce829d2.png)

-- cabinets and devices:
![dcm3](https://cloud.githubusercontent.com/assets/10425179/9404646/f2ab1ac4-47f9-11e5-9d6d-7caf61c4e51e.png)
![dcm4](https://cloud.githubusercontent.com/assets/10425179/9404650/f7e514c2-47f9-11e5-90ed-31278f38c295.png)

And so, Intel DCM: Energy Director very intensively uses the ipmitool for monitoring of CPU load and temperature in the equipment. Also it is very good idea.

But bank, the owner of two DCs, doesn't want to buy yet APC DC Optimize or Intel DCM: Energy Director. The first program isn't bought, because it costs very-very much, there are a lot of excess and not necessary functions, it is difficult to add the new equipment, etc. And the second program isn't bought, because it works only with Intel-based processor systems. And the banking sector, very often uses for computation not of Intel-based servers, and IBM servers with PowerPC processors for running IBM AIX OS. And it already absolutely other architecture...

Very thanks for the support.

**Comment by MorinPierre** [comment]
I already thought about measuring CPU usage, such functionality should be easy to implement. I organized my code to be a base for new MP. I won't do it because I only have a week left before I leave this job but somebody from the community will be able to do that. As I said, I'll keep answering questions.

**Comment by spezialist1** [comment]
Pierre, if not a secret, tell, please, why only until the end of the next week? Than this project is for you? As so left that you were engaged in this project and already want it to leave?
I'm sorry for my curiosity :-).

Very thanks for the support.

**Comment by MorinPierre** [comment]
It's not a secret :). I am working on this project as a internship to finish my studies. It ends by the end of the month. After that, I'll have to find a job etc. I won't have the time to continue this project.

**Comment by spezialist1** [comment]
Hi Pierre,

In that case is a just very fine project for internship! I wish to find interesting and adequately paid job :-).

24.08.2015 10:44, MorinPierre notifications@github.com

> It's not a secret :). I am working on this project as a internship to finish my studies. It ends by the end of the month. After that, I'll have to find a job etc. I won't have the time to continue this project.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/33#issuecomment-134075817

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
Thank you :)

**Comment by spezialist1** [comment]
P.S.: I forgot to tell: the finish of your internship -- is an implementation in **production** openDCIM with PUE and DCEM in two DCs for one of commercial banks of Ukraine. I think, you can fairly write this fact to yourself in bonuses and an asset ;-). Good job!
I will be glad something to you to you to help if it is possible :-).

24.08.2015 11:06, MorinPierre notifications@github.com

> Thank you :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/33#issuecomment-134084480

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
That would be nice indeed. Can I have the name of the bank please?

**Comment by spezialist1** [comment]
Yes, of course, is JSC "Oschadbank". Unfortunately, I can't provide the valid documentary confirmation of it: Pierre, you understand, banks very much don't wish to tell about what software/hardware and what vendor they use. For them, it is a commercial secret :-).

24.08.2015 14:36, MorinPierre notifications@github.com

> That would be nice indeed. Can I have the name of the bank please?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MorinPierre/openDCIM/issues/33#issuecomment-134162484

## 

Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by MorinPierre** [comment]
It is more than enough, thank you.
