### ISSUE TITLE
graphgenerator: more correct display of energy?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#34]
Pierre, I think that it is better to change the graph of energy in graphgenerator. Now in openDCIM this graph actually displays the instantaneous relative consuming of energy what to eat is unusual and tangled for the graph of this kind:
![energy_graph](https://cloud.githubusercontent.com/assets/10425179/9465313/542953dc-4b34-11e5-957a-8d4a8c7fbc63.png)

It seems to me, it is better to remake and make the graph of energy it the simply linear, i.e. the graph shall show absolute values of the consumed energy, for example here so (both graphs week for the same device):
![energy_graph_apc](https://cloud.githubusercontent.com/assets/10425179/9465338/781e927a-4b34-11e5-9ba3-01736ea706be.png)

Very thanks for the support.

**Comment by MorinPierre** [comment]
Try to change the frequency. You'll get something like you sent.

**Comment by spezialist1** [comment]
Pierre, this is daily:
![energy_daily](https://cloud.githubusercontent.com/assets/10425179/9466274/565906ae-4b3c-11e5-955c-6eeecf82e870.png)

and this is monthly:
![energy_monthly](https://cloud.githubusercontent.com/assets/10425179/9466276/63d96d50-4b3c-11e5-84c8-edbf7d43b315.png)

As you see, the same result. This device has Energy OID and is polled each 5 minutes.

Very thanks for the support.

**Comment by MorinPierre** [comment]
I misunderstood. You want to display the counter rather than the consumption on each period. Am I right?

**Comment by spezialist1** [comment]
Yes, everything is correct, the energy counter.

In my opinion, the energy counter is more clear graph, than energy consuming. The matter is that it is possible to estimate energy consuming from the power graphs. Quite so energy is displayed in all DCM-like software, with which I worked and I work.

Very thanks for the support.

**Comment by spezialist1** [comment]
Pierr, thanks for addition: both types of graphs of energy are displayed correctly.

Very thanks for the support.
