### ISSUE TITLE
Minimum allowed time of polling ElectricalMP for the accounting of energy?

### ISSUE THREAD

**Issue by spezialist1** [MorinPierre/openDCIM#35]
Pierre, there is one nuance in case of a choice of polling time of ElectricalMP for the accounting of energy, if appropriate Energy OID is absent (computation of energy is executed arithmetically). For example, if polling of ElectricalMP is executed each five-ten minutes and power doesn't exceed 1kW, the calculated energy will always be equal 0kWh.
Thus, for the same ElectricalMP for saving accuracy in polling of power (for CDU and power panels in openDCIM), the time of polling needs to be reduced (several times in an hour). But at the same time, for correct polling of energy of the same ElectricalMP the time of polling needs to be increased (not more often than once an hour).

Conclusion: if there is ElectricalMP without Energy OID, this ElectricalMP needs to be divided into two separate ElectricalMP. ElectricalMP(power) will be often polled, and ElectricalMP(energy) will be polled not often. So far only thus, it is possible to reach the acceptable results.

Very thanks for the support.

**Comment by MorinPierre** [comment]
That's right. This possibility of measuring the energy is here to help people who haven't a lot of measurement equipments. It is very imprecise, particularly on the long term. On each measure you loose a part of the energy that is consumed.

**Comment by MorinPierre** [comment]
The problem can be solved by keeping this lost part somewhere. I'll think about it.

**Comment by spezialist1** [comment]
Pierre, this problem still can be solved, writing in the table during a polling not of kWh, but Wh. Then, even at the power of 100W the acceptable polling with the period of 5-10 minutes as a result of which, energy will be normally calculated will become possible.
However, thus in all remaining calculations in php-scripts it will be necessary to remember, that values of energy from the table need to be increased on 1000 for receiving kWh.

It seems to me, is the simplest and logical decision.

Very thanks for the support.

**Comment by MorinPierre** [comment]
That's how I planned to do it.

**Comment by MorinPierre** [comment]
You'll have to change your energy measures. Use this SQL query:
UPDATE fac_ElectricalMeasure SET Energy = Energy \* 1000;

**Comment by spezialist1** [comment]
Pierre, the correct values of energy in Wh normally recorded in the updated table fac_ElectricalMeasure. But these values of energy aren't displayed on the page of editing measure points (the field 'Energy' on this page empty, contains nothing).

**Comment by MorinPierre** [comment]
Does it work now? It works for me.

**Comment by spezialist1** [comment]
Yes, it is works, now everything is normal.

Now I will collect updated statistics on energy for some days and I will look as PUE and DCEM will change.

Very thanks for the support.

**Comment by spezialist1** [comment]
Pierre, after the made changes (in measure.inc.php) in ElectricalMP value of energy again isn't displayed. This bug belongs only to ElectricalMP at which measurement is performed only on one OID. If in ElectricalMP all three OID are specified, value of energy is normally displayed on the page of editing MP.
I again checked: the correct values of energy in Wh normally recorded in the table fac_ElectricalMeasure.

Very thanks for the support.

**Comment by MorinPierre** [comment]
The float issue again...

**Comment by MorinPierre** [comment]
I changed Energy data type to DOUBLE. It's more logical.

**Comment by MorinPierre** [comment]
Oh, and you have to divide the energy by 1000:
UPDATE fac_ElectricalMeasure SET Energy = Energy / 1000;

**Comment by spezialist1** [comment]
Pierre, in each 5 minutes at the power 230W there shall be an increase in the consumed energy approximately on 19Wh. But after last modifications, apparently from the table, it doesn't occur:
![energy_meas](https://cloud.githubusercontent.com/assets/10425179/9549266/cbc3ee18-4dad-11e5-9db2-f3ffc01ef67d.png)

Very thanks for the support.

**Comment by MorinPierre** [comment]
Is the power measured from amperes?

**Comment by spezialist1** [comment]
Yes, from amperes.

**Comment by MorinPierre** [comment]
Last commit should fix it.

**Comment by spezialist1** [comment]
Pierre, thanks for fix, electrical measurements writed correctly.

P.S.: you after all, really won't be stop further development this project?

**Comment by spezialist1** [comment]
:-) Pierre, now energy with modbus-devices is incorrectly recorded in DB: in the table always recorded value of energy is '1'. My modbus-devices have the energy register (energy not calculated from power).

Very thanks for the support.

**Comment by spezialist1** [comment]
Too most treats and snmp-devices with energy multiplier equal 0.01 and with OID energy.

**Comment by spezialist1** [comment]
Pierre, I congratulate! Just I checked measurements of energy on all the different ElectricalMP: all measurements are polled correctly :-).

Very thanks for the support.
